### ISSUE TITLE
Password reset is Broken

### ISSUE THREAD

**Issue by fccoelho** [gigantum/gigantum-desktop#94]
**Describe the bug**
Password reset mechanism let's me change the password but then does not accept the new password. By the way, how many old-password are remembered? Last five?

it does not give a bad password message, but the following:
```
We're sorry, something went wrong when attempting to log in.
```

**Configuration**
 - OS: Ubuntu 
 - Version: 19.10

**Comment by dkleissa** [comment]
@fccoelho -  we have not been able to reproduce this ourselves, but have had a few reports of other users running into it. We believe this to be an issue with 3rd party cookies related to our authentication provider, but aren't 100% sure since we can't manage to exactly reproduce. We actually rolled out an update this evening that will resolve 3rd party cookie issues, so hopefully the password reset issue will be resolved as well. We're continuing to monitor this and may apply some additional fixes over the next day or two.

We have heard that if you try a different web browser to complete the reset it works.

Regarding password re-use. The last 3 passwords are not available for reuse.

**Comment by fccoelho** [comment]
Thanks for the suggested work around. I've tried and it worked: I changed the password in one browser and then logged in (with the new password) on another.
